name: release

on:
  push:
    tags: [v*.*.*]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          body: "EDJX C++ SDK"
          artifacts: "distrib/*"
          token: ${{ secrets.GITHUB_TOKEN }}